allowBuilds:
  '@mongodb-js/zstd': false
  '@parcel/watcher': false
  '@swc/core': false
  cbor-extract: false
  esbuild: false
  maplibre-gl: false
  msgpackr-extract: false
  node-liblzma: false
  unrs-resolver: false
  vue-demi: false
  workerd: true

blockExoticSubdeps: false

ignoredBuiltDependencies:
  - '@vercel/speed-insights'

minimumReleaseAgeExclude:
  - '@nuxt/kit-nightly@5.0.0-29776765.204647f9'
  - '@nuxt/nitro-server-nightly@5.0.0-29776765.204647f9'
  - '@nuxt/schema-nightly@5.0.0-29776765.204647f9'
  - '@nuxt/vite-builder-nightly@5.0.0-29776765.204647f9'
  - nuxt-nightly@5.0.0-29776765.204647f9
  - unrouting@0.2.3
  - '@chat-adapter/shared@4.38.0'
  - '@chat-adapter/telegram@4.38.0'
  - chat@4.38.0
overrides:
  '@vite-hub/schedule': https://pkg.pr.new/vite-hub/vitehub/@vite-hub/schedule@d7519b0

patchedDependencies:
  '@vite-hub/email@0.0.1': patches/@vite-hub__email@0.0.1.patch
  '@vite-hub/kv@0.0.1': patches/@vite-hub__kv@0.0.1.patch
  '@vite-hub/schedule@0.0.1': patches/@vite-hub__schedule@0.0.1.patch
  '@vite-hub/workflow@0.0.1': patches/@vite-hub__workflow@0.0.1.patch
  nuxt-og-image@6.7.8: patches/nuxt-og-image@6.7.8.patch
  vite-hub@0.0.1: patches/vite-hub@0.0.1.patch
