allowBuilds:
  '@mongodb-js/zstd': false
  '@parcel/watcher': false
  '@swc/core': false
  cbor-extract: false
  esbuild: false
  maplibre-gl: false
  msgpackr-extract: false
  node-liblzma: false
  unrs-resolver: false
  vue-demi: false
  workerd: true

blockExoticSubdeps: false

ignoredBuiltDependencies:
  - '@vercel/speed-insights'

minimumReleaseAgeExclude:
  - '@nuxt/kit-nightly@5.0.0-29788537.bc41aa9c'
  - '@nuxt/nitro-server-nightly@5.0.0-29788537.bc41aa9c'
  - '@nuxt/schema-nightly@5.0.0-29788537.bc41aa9c'
  - '@nuxt/vite-builder-nightly@5.0.0-29788537.bc41aa9c'
  - nuxt-nightly@5.0.0-29788537.bc41aa9c
  - unrouting@0.2.3
  - '@chat-adapter/shared@4.38.0'
  - '@chat-adapter/telegram@4.38.0'
  - chat@4.38.0

overrides:
  '@vite-hub/source': 'https://pkg.pr.new/vite-hub/vitehub/@vite-hub/source@a612a4894461de04d34c72a229bb6e531410e8b9'
