name = "my-pull-requests"
account_id = "ba6e044dfdaaffec3cac45e9feccd237"
main = ".output/server/index.mjs"
compatibility_date = "2026-06-30"

[assets]
directory = ".output/public"

[[kv_namespaces]]
binding = "KV"
id = "95ebec0a7edc49eeb70a9fe1500bbd83"
